name: Create and publish a local container

on:
  push:
    branches:
      - "*"

env:
  SETUP_BUILDX_VERSION: "latest"
  SETUP_BUILDKIT_IMAGE: "moby/buildkit:latest"
  REGISTRY: container.devops
  IMAGE_NAME: builder
  PLATFORMS: "linux/amd64"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    container: 
      image: gitea/runner-images:ubuntu-latest
      volumes: 
        - /var/run/docker.sock:/var/run/docker.sock
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trust private registry
        run: |
          apt-get update
          apt-get install -y ca-certificates
          cp ca.crt /usr/local/share/ca-certificates
          update-ca-certificates

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildkitd
        with:
          version: ${{ env.SETUP_BUILDX_VERSION }}
          driver-opts: image=${{ env.SETUP_BUILDKIT_IMAGE }}
          buildkitd-flags: --debug
          buildkitd-config-inline: |
            [registry."${{ env.REGISTRY }}"]
              http = false
              insecure = true

      - name: Prep build
        run: |
          cp ~/.docker/config.json $GITHUB_WORKSPACE/

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        id: push
        with:
          builder: ${{ steps.buildkitd.outputs.name }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          platforms: ${{ env.PLATFORMS }}
          context: .
          cache-from: ''
          cache-to: ''
