{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "gitea-runner.fullname" . }}
  labels: {{- include "gitea-runner.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: {{ .Values.persistentVolume.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ template "gitea-runner.fullname" . }}
          operator: In
          values:
          - local
{{- end }}